/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Header from "../../public/Components/Header";
import Footer from "../../public/Components/Footer";
import Link from "next/link";

export async function getServerSideProps(context) {
  const { req } = context;
  const protocol = req.headers.referer
    ? req.headers.referer.split(":")[0]
    : "http";
  const host = req.headers.host;

  const hostUrl = `${protocol}://${host}`;
  try {
    const res = await fetch(`${hostUrl}/api/opportunities`, {
      headers: {
        "Content-Type": "application/json",
      },
    });

    const opportunities = await res.json();

    return {
      props: { data: JSON.stringify(opportunities) },
    };
  } catch (error) {
    return {
      props: { data: "Error" },
    };
  }
}

export default function Home({ data }) {
  let opportunities;
  try {
    opportunities = JSON.parse(data);
  } catch (error) {
    opportunities = "Error";
  }

  console.log(opportunities);
  return (
    <>
      <Head>
        <title>Networks For Growing Berries</title>
        <meta name="description" content="Generated by react" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header showBackButton = {false} />

        <div style={{ marginBottom: 70 }} className="container">
          <div className="rectangle">
            <p>More than volunteering</p>
            <p>Join us for meaningful volunteering</p>
            <p>
              Experiences that connect a wide variety of populations to farmers
              who need help
            </p>
            <Link href="/About" legacyBehavior>
              <a className="button">Learn MORE</a>
            </Link>
          </div>

          <h2 style={{ marginTop: 40 }} className="selection-heading">
            SELECTION BY REGION
          </h2>
          <div className="region-container">
            <div className="region">
              CENTRAL
              <p>100K+ Opportunities</p>
            </div>
            <div className="region">
              NORTH
              <p>200K+ Opportunities</p>
            </div>
            <div className="region">
              WEST
              <p>100K+ Opportunities</p>
            </div>
          </div>

          <h2 style={{ marginTop: 40 }} className="next-to-you">
            NEXT TO YOU
          </h2>
          <div className="farm-container">
            {opportunities.data &&
              opportunities.data.map((opportunity, i) => (
                <Link
                  key={i}
                  href={`/opportunity/${opportunity._id}`}
                  passHref
                  className="farm-link"
                >
                  <div className="farm">
                    <img
                      src={`/Images/${opportunity.header_image}`}
                      alt="Farm 1"
                    />
                    <p>{opportunity.title}</p>

                    <div className="rating">
                      {Array.from({
                        length: Math.floor(opportunity.rating.score),
                      }).map((star, i) => (
                        <>
                          <input
                            key={i}
                            type="radio"
                            id={`star${i + 1}`}
                            name={`rating${i + 1}`}
                            value={i}
                          />
                          <label
                            key={i}
                            className="yellow"
                            htmlFor={`star${i + 1}`}
                          >
                            &#9733;
                          </label>
                        </>
                      ))}
                      {Array.from({
                        length: 5 - Math.floor(opportunity.rating.score),
                      }).map((star, i) => (
                        <>
                          <input
                            key={i}
                            type="radio"
                            id={`star${i + 1}`}
                            name={`rating${i + 1}`}
                            value={i}
                          />
                          <label
                            key={i}
                            className="gray"
                            htmlFor={`star${i + 1}`}
                          >
                            &#9733;
                          </label>
                        </>
                      ))}
                    </div>
                  </div>
                </Link>
              ))}

            {/* <a href="farm2-page.html" className="farm-link">
              <div className="farm">
                <img src="/Images/R.jpeg" alt="Farm 2" />
                <p>משק חקלאי במושב רוויה</p>

                <div className="rating">
                  <input type="radio" id="star6" name="rating2" value="1" />
                  <label htmlFor="star6">&#9733;</label>
                  <input type="radio" id="star7" name="rating2" value="2" />
                  <label htmlFor="star7">&#9733;</label>
                  <input type="radio" id="star8" name="rating2" value="3" />
                  <label htmlFor="star8">&#9733;</label>
                  <input type="radio" id="star9" name="rating2" value="4" />
                  <label htmlFor="star9">&#9733;</label>
                  <input type="radio" id="star10" name="rating2" value="5" />
                  <label htmlFor="star10">&#9733;</label>
                </div>
              </div>
            </a>

            <a href="farm3-page.html" className="farm-link">
              <div className="farm">
                <img src="/Images/tal.jpg" alt="Farm 3" />
                <p>משק טל נעורים</p>

                <div className="rating">
                  <input type="radio" id="star11" name="rating3" value="1" />
                  <label htmlFor="star11">&#9733;</label>
                  <input type="radio" id="star12" name="rating3" value="2" />
                  <label htmlFor="star12">&#9733;</label>
                  <input type="radio" id="star13" name="rating3" value="3" />
                  <label htmlFor="star13">&#9733;</label>
                  <input type="radio" id="star14" name="rating3" value="4" />
                  <label htmlFor="star14">&#9733;</label>
                  <input type="radio" id="star15" name="rating3" value="5" />
                  <label htmlFor="star15">&#9733;</label>
                </div>
              </div>
            </a> */}
          </div>

          <h2 style={{ marginTop: 40 }} className="all-opportunities">
            ALL THE OPPORTUNITIES
          </h2>
          <div className="opportunity-container">
            {opportunities.data &&
              opportunities.data.map((opportunity, i) => (
                <Link
                  style={{ textDecoration: "none" }}
                  key={i}
                  href={`/opportunity/${opportunity._id}`}
                  className="opportunity"
                  passHref
                >
                  <img
                    src={`/Images/${opportunity.header_image}`}
                    alt="Opportunity"
                  />
                  <div className="opportunity-text">
                    <p className="title">{opportunity.title}</p>
                    <p className="description">{opportunity.description}</p>
                  </div>
                </Link>
              ))}
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
